/*
        Each new term in the Fibonacci sequence is generated by adding the previous two terms.

        By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Main {
    public static void main(String[] args) {

        System.out.println("Sum of all even Ferbonacci number is: " +sumofeven() );

    }

    public static int sumofeven() {
        int sum = 0;
        int num1 = 0;
        int num2 = 1;
        int num3 = num1 + num2;
        int limit = 4000000;
        while (num3 < limit) {
            if (num3 % 2 == 0) {
                sum = sum + num3;
            }
            num1 = num2;
            num2 = num3;
            num3 = num1 + num2;
        }
        return sum;
    }
}
